workspace:
  base: /go
  path: src/github.com/wyattjoh/drone-gcs

pipeline:
  test:
    image: golang:1.8
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: plugins/docker
    repo: wyattjoh/drone-gcs
    tags:
      - latest
      - 1.0
      - 1
    when:
      branch: master
      event: push

plugin:
  name: GCS
  desc: Publish files and artifacts to Google Cloud Storage
  type: publish
  image: wyattjoh/drone-gcs
  labels:
    - publish
    - artifacts
    - google cloud
    - gcp
    - gcs
